export const data = [
	{
		url: "https://api.github.com/repos/Kikozy/TestBlog/issues/2",
		repository_url: "https://api.github.com/repos/Kikozy/TestBlog",
		labels_url: "https://api.github.com/repos/Kikozy/TestBlog/issues/2/labels{/name}",
		comments_url: "https://api.github.com/repos/Kikozy/TestBlog/issues/2/comments",
		events_url: "https://api.github.com/repos/Kikozy/TestBlog/issues/2/events",
		html_url: "https://github.com/Kikozy/TestBlog/issues/2",
		id: 1309308009,
		node_id: "I_kwDOHrRAa85OCnRp",
		number: 2,
		title: "这是一篇测试文章02",
		user: {
			login: "Kikozy",
			id: 48023496,
			node_id: "MDQ6VXNlcjQ4MDIzNDk2",
			avatar_url: "https://avatars.githubusercontent.com/u/48023496?v=4",
			gravatar_id: "",
			url: "https://api.github.com/users/Kikozy",
			html_url: "https://github.com/Kikozy",
			followers_url: "https://api.github.com/users/Kikozy/followers",
			following_url: "https://api.github.com/users/Kikozy/following{/other_user}",
			gists_url: "https://api.github.com/users/Kikozy/gists{/gist_id}",
			starred_url: "https://api.github.com/users/Kikozy/starred{/owner}{/repo}",
			subscriptions_url: "https://api.github.com/users/Kikozy/subscriptions",
			organizations_url: "https://api.github.com/users/Kikozy/orgs",
			repos_url: "https://api.github.com/users/Kikozy/repos",
			events_url: "https://api.github.com/users/Kikozy/events{/privacy}",
			received_events_url: "https://api.github.com/users/Kikozy/received_events",
			type: "User",
			site_admin: false,
		},
		labels: [
			{
				id: 4341502608,
				node_id: "LA_kwDOHrRAa88AAAABAsYSkA",
				url: "https://api.github.com/repos/Kikozy/TestBlog/labels/TypeScript",
				name: "TypeScript",
				color: "1D76DB",
				default: false,
				description: "",
			},
			{
				id: 4341503850,
				node_id: "LA_kwDOHrRAa88AAAABAsYXag",
				url: "https://api.github.com/repos/Kikozy/TestBlog/labels/ES6",
				name: "ES6",
				color: "FBCA04",
				default: false,
				description: "",
			},
			{
				id: 4341504540,
				node_id: "LA_kwDOHrRAa88AAAABAsYaHA",
				url: "https://api.github.com/repos/Kikozy/TestBlog/labels/CSS",
				name: "CSS",
				color: "B60205",
				default: false,
				description: "",
			},
		],
		state: "open",
		locked: false,
		assignee: null,
		assignees: [],
		milestone: {
			url: "https://api.github.com/repos/Kikozy/TestBlog/milestones/3",
			html_url: "https://github.com/Kikozy/TestBlog/milestone/3",
			labels_url: "https://api.github.com/repos/Kikozy/TestBlog/milestones/3/labels",
			id: 8212996,
			node_id: "MI_kwDOHrRAa84AfVIE",
			number: 3,
			title: "游戏",
			description: null,
			creator: {
				login: "Kikozy",
				id: 48023496,
				node_id: "MDQ6VXNlcjQ4MDIzNDk2",
				avatar_url: "https://avatars.githubusercontent.com/u/48023496?v=4",
				gravatar_id: "",
				url: "https://api.github.com/users/Kikozy",
				html_url: "https://github.com/Kikozy",
				followers_url: "https://api.github.com/users/Kikozy/followers",
				following_url: "https://api.github.com/users/Kikozy/following{/other_user}",
				gists_url: "https://api.github.com/users/Kikozy/gists{/gist_id}",
				starred_url: "https://api.github.com/users/Kikozy/starred{/owner}{/repo}",
				subscriptions_url: "https://api.github.com/users/Kikozy/subscriptions",
				organizations_url: "https://api.github.com/users/Kikozy/orgs",
				repos_url: "https://api.github.com/users/Kikozy/repos",
				events_url: "https://api.github.com/users/Kikozy/events{/privacy}",
				received_events_url: "https://api.github.com/users/Kikozy/received_events",
				type: "User",
				site_admin: false,
			},
			open_issues: 1,
			closed_issues: 0,
			state: "open",
			created_at: "2022-07-19T10:23:50Z",
			updated_at: "2022-07-19T10:23:52Z",
			due_on: null,
			closed_at: null,
		},
		comments: 0,
		created_at: "2022-07-19T10:23:52Z",
		updated_at: "2022-11-21T08:35:51Z",
		closed_at: null,
		author_association: "OWNER",
		active_lock_reason: null,
		body: "《雨巷》是中国诗人戴望舒1927年创作的一首现代诗。诗中描写了抒情主人公“撑着油纸伞”，独自彷徨在悠长而又寂寥的雨巷。他怀着一种缥缈的希望，希望逢着“一个丁香一样地结着愁怨的姑娘”，这个姑娘有着丁香一样的颜色与芬芳，而她的内心却结着忧愁、哀怨。他逢着了这样的姑娘，然而转瞬即逝，“像梦中飘过”，她的颜色、芬芳、“太息般的眼光”以及“丁香般的惆怅”统统消散在“雨的哀曲里”。他依旧“撑着油纸伞”，独自彷徨在悠长而又寂寥的雨巷，依旧怀着希望，希望飘过“一个丁香一样地结着愁怨的姑娘”。\r\n《雨巷》中，诗人用象征性的意象及意象群来营建抒情空间，传达内心情感，并且融会了中国古代诗歌，尤其是晚唐五代纤弱婉约诗词的艺术营养。不仅如此，这首诗在艺术上的成功之处还在于它的和谐的音律美。\r\n\r\n## 节流(Throttle)\r\n这里的核心主要是通过timer的null来判断，当为null时就执行延迟函数，当不是null时就重新创建一个新的延迟函数。这样就能确保在规定的时间内只执行一次延迟函数。\r\n\r\n这里利用了闭包，实际执行的方法是内部的function，内部的function在每次触发都能访问到timer。\r\n\r\n``` javascript\r\n\r\nfunction debounceFun(fn, delay) {\r\n  let timer\r\n  return function () {\r\n    clearTimeout(timer) //每次触发都清除定时器\r\n    timer = setTimeout(fn, delay) //每次触发都重新创建一个定时器\r\n  }\r\n}\r\n\r\n```\r\n\r\n## 防抖(Debounce)\r\n\r\n> 事件频繁触发的情况下，只有经过足够的空闲时间，才执行代码一次。\r\n\r\n这里利用了闭包，实际使用的是内部返回的function 这个function保留了debounceFun函数中的timer变量，这样才使得每次触发的时候都能访问到timer。\r\n``` TypeScript\r\n\r\nfunction debounceFun(fn, delay) {\r\n  let timer\r\n  return function () {\r\n    clearTimeout(timer) //每次触发都清除定时器\r\n    timer = setTimeout(fn, delay) //每次触发都重新创建一个定时器\r\n  }\r\n}\r\n\r\n```\r\n\r\n### Map\r\n\r\n> `Map` 是键值对的集合，但是键可以是任意值，甚至是对象\r\n> `Map` 是一种更完善的Hash结构实现\r\n\r\n**Set方法**\r\n- set(key,value) 增加一个新成员 键为key，值为value\r\n- get(key) 返回与key关联的值，若不存在，则返回undefined\r\n- clear() 清除所有成员\r\n- delete(value) 删除值为value的元素，会返回一个boolean来表示成功和失败\r\n- has(value) 返回一个boolean来表示该值是否存在\r\n\r\n**迭代方法**\r\n- keys() 迭代器key\r\n- values() 迭代器value\r\n\r\n![MIKU_01](https://user-images.githubusercontent.com/48023496/180720425-6ea21e8d-2e26-4a98-a5c4-b2b22d8a085a.jpg)\r\n![MIKU_02](https://user-images.githubusercontent.com/48023496/180720304-aecce15c-e30d-45f1-b9ac-85a081e05eef.jpg)\r\n![MIKU_03](https://user-images.githubusercontent.com/48023496/180720311-51bf38c5-e92e-42e6-9864-404e74cc1aec.jpg)",
		reactions: {
			url: "https://api.github.com/repos/Kikozy/TestBlog/issues/2/reactions",
			total_count: 0,
			"+1": 0,
			"-1": 0,
			laugh: 0,
			hooray: 0,
			confused: 0,
			heart: 0,
			rocket: 0,
			eyes: 0,
		},
		timeline_url: "https://api.github.com/repos/Kikozy/TestBlog/issues/2/timeline",
		performed_via_github_app: null,
		state_reason: null,
	},
	{
		url: "https://api.github.com/repos/Kikozy/TestBlog/issues/1",
		repository_url: "https://api.github.com/repos/Kikozy/TestBlog",
		labels_url: "https://api.github.com/repos/Kikozy/TestBlog/issues/1/labels{/name}",
		comments_url: "https://api.github.com/repos/Kikozy/TestBlog/issues/1/comments",
		events_url: "https://api.github.com/repos/Kikozy/TestBlog/issues/1/events",
		html_url: "https://github.com/Kikozy/TestBlog/issues/1",
		id: 1309007297,
		node_id: "I_kwDOHrRAa85OBd3B",
		number: 1,
		title: "JavaScript这是一篇测试文章01",
		user: {
			login: "Kikozy",
			id: 48023496,
			node_id: "MDQ6VXNlcjQ4MDIzNDk2",
			avatar_url: "https://avatars.githubusercontent.com/u/48023496?v=4",
			gravatar_id: "",
			url: "https://api.github.com/users/Kikozy",
			html_url: "https://github.com/Kikozy",
			followers_url: "https://api.github.com/users/Kikozy/followers",
			following_url: "https://api.github.com/users/Kikozy/following{/other_user}",
			gists_url: "https://api.github.com/users/Kikozy/gists{/gist_id}",
			starred_url: "https://api.github.com/users/Kikozy/starred{/owner}{/repo}",
			subscriptions_url: "https://api.github.com/users/Kikozy/subscriptions",
			organizations_url: "https://api.github.com/users/Kikozy/orgs",
			repos_url: "https://api.github.com/users/Kikozy/repos",
			events_url: "https://api.github.com/users/Kikozy/events{/privacy}",
			received_events_url: "https://api.github.com/users/Kikozy/received_events",
			type: "User",
			site_admin: false,
		},
		labels: [
			{
				id: 4341404705,
				node_id: "LA_kwDOHrRAa88AAAABAsSUIQ",
				url: "https://api.github.com/repos/Kikozy/TestBlog/labels/JavaScript",
				name: "JavaScript",
				color: "B74B09",
				default: false,
				description: "",
			},
			{
				id: 4364439804,
				node_id: "LA_kwDOHrRAa88AAAABBCQQ_A",
				url: "https://api.github.com/repos/Kikozy/TestBlog/labels/%E6%B5%8B%E8%AF%95%E4%B8%80%E4%B8%8B%E5%93%A6",
				name: "测试一下哦",
				color: "AAAAAA",
				default: false,
				description: "",
			},
		],
		state: "open",
		locked: false,
		assignee: null,
		assignees: [],
		milestone: {
			url: "https://api.github.com/repos/Kikozy/TestBlog/milestones/1",
			html_url: "https://github.com/Kikozy/TestBlog/milestone/1",
			labels_url: "https://api.github.com/repos/Kikozy/TestBlog/milestones/1/labels",
			id: 8211752,
			node_id: "MI_kwDOHrRAa84AfU0o",
			number: 1,
			title: "前端",
			description: null,
			creator: {
				login: "Kikozy",
				id: 48023496,
				node_id: "MDQ6VXNlcjQ4MDIzNDk2",
				avatar_url: "https://avatars.githubusercontent.com/u/48023496?v=4",
				gravatar_id: "",
				url: "https://api.github.com/users/Kikozy",
				html_url: "https://github.com/Kikozy",
				followers_url: "https://api.github.com/users/Kikozy/followers",
				following_url: "https://api.github.com/users/Kikozy/following{/other_user}",
				gists_url: "https://api.github.com/users/Kikozy/gists{/gist_id}",
				starred_url: "https://api.github.com/users/Kikozy/starred{/owner}{/repo}",
				subscriptions_url: "https://api.github.com/users/Kikozy/subscriptions",
				organizations_url: "https://api.github.com/users/Kikozy/orgs",
				repos_url: "https://api.github.com/users/Kikozy/repos",
				events_url: "https://api.github.com/users/Kikozy/events{/privacy}",
				received_events_url: "https://api.github.com/users/Kikozy/received_events",
				type: "User",
				site_admin: false,
			},
			open_issues: 1,
			closed_issues: 0,
			state: "open",
			created_at: "2022-07-19T05:43:29Z",
			updated_at: "2022-07-19T05:43:29Z",
			due_on: null,
			closed_at: null,
		},
		comments: 1,
		created_at: "2022-07-19T05:42:14Z",
		updated_at: "2022-11-17T09:39:35Z",
		closed_at: null,
		author_association: "OWNER",
		active_lock_reason: null,
		body: "《再别康桥》是[现代诗人][徐志摩]脍炙人口的诗篇，是[新月派]诗歌的代表作品。全诗以离别康桥时感情起伏为线索，抒发了对康桥依依惜别的深情。语言轻盈柔和，形式精巧圆熟，诗人用虚实相间的手法，描绘了一幅幅流动的画面，构成了一处处美妙的意境，细致入微地将诗人对康桥的爱恋，对往昔生活的怀念，对眼前的无可奈何的离愁，表现得真挚、浓郁、隽永，是徐志摩诗作中的绝唱。\r\n\r\n\r\n\r\n> 哇大王的 @哇大大\r\n```\r\nconsole.log('gg')\r\n```\r\n哇哦哦哦\r\n",
		reactions: {
			url: "https://api.github.com/repos/Kikozy/TestBlog/issues/1/reactions",
			total_count: 0,
			"+1": 0,
			"-1": 0,
			laugh: 0,
			hooray: 0,
			confused: 0,
			heart: 0,
			rocket: 0,
			eyes: 0,
		},
		timeline_url: "https://api.github.com/repos/Kikozy/TestBlog/issues/1/timeline",
		performed_via_github_app: null,
		state_reason: null,
	},
]
